### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by ai2010** [jakemmarsh/neural-network-stock-predictor#2]
Hi,

I successfully installed the code and end up in the home page (index.html) using 'npm start'. What should I do from there? How do I run it? Thanks

**Comment by jeffreyyong** [comment]
Hi Jake,

Thank you for the repo. However the page seems to be empty after running `npm start`. 

I am wondering how I can interact with the website? This is what I see:
<img width="1413" alt="screen shot 2016-12-09 at 12 52 36" src="https://cloud.githubusercontent.com/assets/13610813/21049766/a5a1f04a-be0e-11e6-84f0-31416dfc9d9f.png">

Thanks, 
Jeffrey

**Comment by MonaTanggg** [comment]
@jeffreyyong I''m facing the same problem, did you find any solution ?

**Comment by jeffreyyong** [comment]
@MonaTanggg No I didn't manage to find a solution, sorry.

**Comment by MeekMonk** [comment]
I couldn't get it to work whenever i type npm start it gives me some error messages and this debug log (also my name is Mac so its not talking about a mac computer):

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Mac\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v6.11.1
4 verbose config Skipping project config: C:\Users\Mac/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: start
5 verbose stack     at run (C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
5 verbose stack     at C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
5 verbose stack     at C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:114:5
5 verbose stack     at C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:401:5
5 verbose stack     at checkBinReferences_ (C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:356:45)
5 verbose stack     at final (C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:399:3)
5 verbose stack     at then (C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:159:5)
5 verbose stack     at ReadFileContext.<anonymous> (C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:331:20)
5 verbose stack     at ReadFileContext.callback (C:\Users\Mac\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
6 verbose cwd C:\Users\Mac
7 verbose Windows_NT 10.0.14393
8 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mac\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
9 verbose node v6.11.1
10 verbose npm  v5.3.0
11 error missing script: start
12 verbose exit [ 1, true ]
